version: "3.8"

services:
  pingme_local:
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: pml
      restart: always
      ports:
        - "8080:8080"
      environment:
        PINGME_ENDPOINT: "pmr:8080"
  pingeme_remote:
      depends_on:
        - "pingme_local"
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: pmr
      restart: always
      ports:
        - "8090:8080"

networks:
  default:
    name: pingme-net
    external: false